// import "@/styles/globals.css";
// import type { AppProps } from "next/app";

// export default function App({ Component, pageProps }: AppProps) {
// 	return <Component {...pageProps} />;
// }

import { AppProps } from 'next/app';
import Head from 'next/head';
import { MantineProvider } from '@mantine/core';

export default function App(props: AppProps) {
  const { Component, pageProps } = props;

  return (
    <>

	  <Head>
			<title>Ekonomi Deneyi</title>
			<meta
				name="description"
				content="Generated by create next app"
			/>
			<meta
				name="viewport"
				content="minimum-scale=1,width=device-width, initial-scale=1"
			/>
			<link rel="icon" href="/belief/favicon.ico" />
		</Head>

      <MantineProvider
        withGlobalStyles
        withNormalizeCSS
        theme={{
          /** Put your mantine theme override here */
          colorScheme: 'light',
        }}
      >
        <Component {...pageProps} />
      </MantineProvider>
    </>
  );
}